### PR TITLE
[minisite] enable to use asciidoctor-java

### PR DESCRIPTION
**Pull request by rmannibucau**
@fpapon we need to discuss it since it is a breaking change for the "asciidoctor pool"

### CODE REVIEW

**Review by fpapon — APPROVED** [review]
Works well, tested on https://www.yupiik.io website generation.

**Comment by rmannibucau** [comment]
@fpapon should we merge that and move the version to 1.2.0-SNAPSHOT since it breaks the minisite asciidoc API?

**Comment by fpapon** [comment]
> @fpapon should we merge that and move the version to 1.2.0-SNAPSHOT since it breaks the minisite asciidoc API?

Yes, I think it make sense to move to 1.2.0!

**Comment by rmannibucau** [comment]
@fpapon upgraded the version in the poms, once the build passes, let's merge :)

**Pull request merged**
